version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ACCOUNT_ID: 147100277727
    CLUSTER_NAME: stayescape-cluster
    IMAGE_TAG: $CODEBUILD_RESOLVED_SOURCE_VERSION

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Using Java version:"
      - java -version
  pre_build:
    commands:
      # Login to ECR
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com


  build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9._-' '-')

      - cd shared-module
      - mvn clean install
      - cd ..
      # Build & push images (Jib)
      - cd auth-service
      - mvn clean compile jib:build -Dimage=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:$IMAGE_TAG
      - cd ..

      - cd user-service
      - mvn clean compile jib:build -Dimage=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-service:$IMAGE_TAG
      - cd ..

      - cd hotel_service
      - mvn clean compile jib:build -Dimage=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hotel-service:$IMAGE_TAG
      - cd ..

      - cd booking-service
      - mvn clean compile jib:build -Dimage=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/booking-service:$IMAGE_TAG
      - cd ..
artifacts:
  files:
    - image_tag.env

